# Generated by Django 5.2.5 on 2025-08-27 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_code', models.CharField(editable=False, max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(max_length=15)),
                ('device_type', models.CharField(max_length=100)),
                ('device_brand', models.CharField(blank=True, max_length=100)),
                ('device_model', models.CharField(blank=True, max_length=100)),
                ('device_serial', models.CharField(blank=True, max_length=100)),
                ('reported_issue', models.TextField()),
                ('additional_items', models.TextField(blank=True, help_text='e.g., Laptop bag, Charger, Mouse')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Under Inspection', 'Under Inspection'), ('Repairing', 'Repairing'), ('Completed', 'Completed'), ('Ready for Pickup', 'Ready for Pickup'), ('Closed', 'Closed')], default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_job_ticket', models.ForeignKey(blank=True, help_text='Link to the original job ticket for re-entry/rework', null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_tickets.jobticket')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('part_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('service_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_logs', to='job_tickets.jobticket')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicianProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=10, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technician_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='jobticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_tickets.technicianprofile'),
        ),
    ]
