# Generated by Django 5.2.5 on 2025-08-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobticket',
            name='technician_notes',
            field=models.TextField(blank=True, help_text='Internal notes for technicians/staff.'),
        ),
    ]
