# Generated by Django 5.2.5 on 2025-08-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0002_jobticket_technician_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobticket',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
