# Generated by Django 5.2.5 on 2025-08-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0004_jobticket_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobticket',
            name='is_under_warranty',
            field=models.BooleanField(default=False, help_text='Check if this job is under company warranty.'),
        ),
    ]
