# Generated by Django 5.2.5 on 2025-09-03 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0005_jobticket_is_under_warranty'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobticket',
            name='estimated_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='jobticket',
            name='estimated_delivery',
            field=models.DateField(blank=True, null=True),
        ),
    ]
