# Generated by Django 5.2.5 on 2025-09-05 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0006_jobticket_estimated_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Current accepted technician (set when assignment accepted)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_tickets.technicianprofile'),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('response_note', models.TextField(blank=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='job_tickets.jobticket')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='job_tickets.technicianprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('job', 'technician')},
            },
        ),
    ]
