# Generated by Django 5.2.5 on 2025-09-24 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0007_alter_jobticket_assigned_to_assignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTicketLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('CREATED', 'Job Created'), ('ASSIGNED', 'Technician Assigned'), ('STATUS', 'Status Changed'), ('NOTE', 'Note Updated'), ('SERVICE', 'Service Log Added/Updated'), ('BILLING', 'Billing Info Updated'), ('CLOSED', 'Job Closed')], max_length=50)),
                ('details', models.TextField(help_text="Description of the change, e.g., 'Status changed from Pending to Repairing'")),
                ('job_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='job_tickets.jobticket')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
