# Generated by Django 5.2.5 on 2025-09-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0008_jobticketlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobticket',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Under Inspection', 'Under Inspection'), ('Repairing', 'Repairing'), ('Returned', 'Returned'), ('Completed', 'Completed'), ('Ready for Pickup', 'Ready for Pickup'), ('Closed', 'Closed')], default='Pending', max_length=50),
        ),
    ]
