# Generated by Django 5.2.5 on 2025-09-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0009_alter_jobticket_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The individual's name or contact person.", max_length=200)),
                ('company_name', models.CharField(help_text='The official name of the vendor company.', max_length=255, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('specialties', models.TextField(blank=True, help_text="Notes on what this vendor specializes in, e.g., 'Motherboard chip-level repair', 'Data recovery'.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
    ]
