# Generated by Django 5.2.5 on 2025-09-28 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0010_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobticket',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Under Inspection', 'Under Inspection'), ('Repairing', 'Repairing'), ('Specialized Service', 'Specialized Service'), ('Returned', 'Returned'), ('Completed', 'Completed'), ('Ready for Pickup', 'Ready for Pickup'), ('Closed', 'Closed')], default='Pending', max_length=50),
        ),
        migrations.CreateModel(
            name='SpecializedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Awaiting Assignment', 'Awaiting Vendor Assignment'), ('Sent to Vendor', 'Sent to Vendor'), ('Returned from Vendor', 'Returned from Vendor')], default='Awaiting Assignment', max_length=50)),
                ('vendor_cost', models.DecimalField(blank=True, decimal_places=2, help_text='The amount we pay the vendor.', max_digits=10, null=True)),
                ('client_charge', models.DecimalField(blank=True, decimal_places=2, help_text='The amount we charge the client for this service.', max_digits=10, null=True)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('returned_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this specialized service.')),
                ('job_ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specialized_service', to='job_tickets.jobticket')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='job_tickets.vendor')),
            ],
        ),
    ]
