# Generated by Django 5.2.5 on 2025-10-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0011_alter_jobticket_status_specializedservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobticket',
            name='customer_group_id',
            field=models.CharField(blank=True, help_text='ID used to group multiple jobs from one customer submission.', max_length=50),
        ),
    ]
