# Generated by Django 5.2.5 on 2025-10-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0012_jobticket_customer_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelog',
            name='sales_invoice_number',
            field=models.CharField(blank=True, help_text='Reference number from the external billing software.', max_length=50, null=True),
        ),
    ]
