# Generated by Django 5.2.5 on 2025-10-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0013_servicelog_sales_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobticket',
            name='vyapar_invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
