# Generated by Django 5.2.5 on 2025-11-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0014_jobticket_vyapar_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianprofile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Disable to prevent assignments without deleting the record.'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to disable this vendor for future assignments.'),
        ),
    ]
