# Generated by Django 5.2.5 on 2025-11-03 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0014_jobticket_vyapar_invoice_number'),
        ('job_tickets', '0015_technicianprofile_is_active_vendor_is_active'),
    ]

    operations = [
    ]
