# Generated by Django 5.2.5 on 2025-11-03 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0016_merge_20251103_2335'),
    ]

    operations = [
    ]
