# Generated by Django 5.2.5 on 2025-11-03 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0017_merge_migrations_fix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicianprofile',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='is_active',
        ),
    ]
