# Generated by Django 5.2.5 on 2025-11-03 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0015_create_default_groups'),
        ('job_tickets', '0018_remove_technicianprofile_is_active_and_more'),
    ]

    operations = [
    ]
