# Generated by Django 5.2.5 on 2025-11-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0019_merge_20251104_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobticket',
            name='is_new_assignment',
            field=models.BooleanField(default=False, help_text='True when job is newly assigned and awaiting technician acknowledgement.'),
        ),
    ]
