# Generated by Django 5.2.5 on 2025-11-13 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0021_dailyjobcodesequence'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyJobCodeSequence',
        ),
    ]
