# Generated by Django 6.0.2 on 2026-02-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0023_dailyjobcodesequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobticket',
            name='feedback_comment',
            field=models.TextField(blank=True, help_text='Customer feedback comment'),
        ),
        migrations.AddField(
            model_name='jobticket',
            name='feedback_date',
            field=models.DateTimeField(blank=True, help_text='When feedback was submitted', null=True),
        ),
        migrations.AddField(
            model_name='jobticket',
            name='feedback_rating',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Customer rating (1-5 stars)', null=True),
        ),
    ]
