# Generated by Django 6.0.2 on 2026-02-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0024_jobticket_feedback_comment_jobticket_feedback_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='BOTGI PVT.LTD', max_length=200)),
                ('logo_url', models.URLField(default='https://ik.imagekit.io/mypzongw2/WhatsApp_Image_2025-07-16_at_09.04.23_cc2d2b6e-removebg-preview.png', max_length=500)),
                ('address', models.TextField(default='Pattambi, Kerala')),
                ('phone1', models.CharField(default='+91 8891740022', max_length=20)),
                ('phone2', models.CharField(blank=True, default='+91 9744480016', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profile',
            },
        ),
    ]
