# Generated by Django 6.0.2 on 2026-02-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0025_companyprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='tagline',
            field=models.CharField(blank=True, default='Computer Service & Sales', max_length=200),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='address',
            field=models.CharField(default='KH Buildings, Pattambi, Kerala', max_length=300),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_name',
            field=models.CharField(default='BOT GI TECH TRADING PRIVATE LIMITED', max_length=200),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='logo_url',
            field=models.URLField(blank=True, help_text='Or use image URL', max_length=500),
        ),
    ]
