# Generated by Django 6.0.2 on 2026-02-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0027_extend_company_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='terms_conditions',
            field=models.TextField(blank=True, default='1. All repairs carry 30 days warranty.\n2. No warranty on physical/liquid damage.\n3. Payment due on delivery.'),
        ),
    ]
