# Generated by Django 6.0.2 on 2026-02-18 16:30

from django.db import migrations, models


def apply_company_defaults(apps, schema_editor):
    CompanyProfile = apps.get_model('job_tickets', 'CompanyProfile')
    profile, _ = CompanyProfile.objects.get_or_create(id=1)

    updates = []

    legacy_names = {'', 'GI Service Billing', 'BOTGI PVT.LTD'}
    if (profile.company_name or '').strip() in legacy_names:
        profile.company_name = 'GI Hostings'
        updates.append('company_name')

    legacy_taglines = {'', 'Computer Service & Sales'}
    if (profile.tagline or '').strip() in legacy_taglines:
        profile.tagline = 'Service Billing'
        updates.append('tagline')

    if not (profile.phone1 or '').strip() or profile.phone1.strip() == '+91 0000000000':
        profile.phone1 = '+919567227005'
        updates.append('phone1')

    if not (profile.website or '').strip():
        profile.website = 'https://gihostings.com'
        updates.append('website')

    if updates:
        profile.save(update_fields=updates)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0028_alter_companyprofile_terms_conditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_name',
            field=models.CharField(default='GI Hostings', max_length=200),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='phone1',
            field=models.CharField(default='+919567227005', max_length=20),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='tagline',
            field=models.CharField(blank=True, default='Service Billing', max_length=200),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='website',
            field=models.URLField(blank=True, default='https://gihostings.com'),
        ),
        migrations.RunPython(apply_company_defaults, noop_reverse),
    ]
