# Generated by Django 6.0.2 on 2026-02-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0029_client_product_and_branding'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_author_name', models.CharField(default='GI HOSTINGS', help_text="Footer author name shown as 'Service Billing by ...'", max_length=200)),
                ('support_phone', models.CharField(default='+91 9567227005', help_text='Customer support phone number displayed in footer.', max_length=20)),
                ('whatsapp_number', models.CharField(default='+91 9567227005', help_text='WhatsApp support number displayed in footer.', max_length=20)),
                ('website', models.URLField(blank=True, default='https://gihostings.com')),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
    ]
