# Generated by Codex on 2026-02-19

from django.db import migrations


OLD_NUMBER = "+91 9567225007"
NEW_NUMBER = "+91 9567227005"


def update_platform_support_numbers(apps, schema_editor):
    PlatformSettings = apps.get_model('job_tickets', 'PlatformSettings')

    for settings in PlatformSettings.objects.all():
        updates = []

        if (settings.support_phone or '').strip() == OLD_NUMBER:
            settings.support_phone = NEW_NUMBER
            updates.append('support_phone')

        if (settings.whatsapp_number or '').strip() == OLD_NUMBER:
            settings.whatsapp_number = NEW_NUMBER
            updates.append('whatsapp_number')

        if updates:
            settings.save(update_fields=updates)


def reverse_platform_support_numbers(apps, schema_editor):
    PlatformSettings = apps.get_model('job_tickets', 'PlatformSettings')

    for settings in PlatformSettings.objects.all():
        updates = []

        if (settings.support_phone or '').strip() == NEW_NUMBER:
            settings.support_phone = OLD_NUMBER
            updates.append('support_phone')

        if (settings.whatsapp_number or '').strip() == NEW_NUMBER:
            settings.whatsapp_number = OLD_NUMBER
            updates.append('whatsapp_number')

        if updates:
            settings.save(update_fields=updates)


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0030_platformsettings'),
    ]

    operations = [
        migrations.RunPython(update_platform_support_numbers, reverse_platform_support_numbers),
    ]
