# Generated by Codex on 2026-02-19

import re
from decimal import Decimal

from django.db import migrations


PRODUCT_SALE_LOG_PATTERN = re.compile(
    r'^Product Sale - (?P<name>.+?) \(Qty: (?P<qty>\d+)\) \[PROD#(?P<product_id>\d+)\]$'
)


def backfill_product_sales(apps, schema_editor):
    Product = apps.get_model('job_tickets', 'Product')
    ServiceLog = apps.get_model('job_tickets', 'ServiceLog')
    ProductSale = apps.get_model('job_tickets', 'ProductSale')

    existing_service_log_ids = set(
        ProductSale.objects.exclude(service_log_id=None).values_list('service_log_id', flat=True)
    )

    candidates = list(
        ServiceLog.objects.filter(description__startswith='Product Sale - ')
        .values('id', 'job_ticket_id', 'description', 'part_cost', 'created_at')
    )
    if not candidates:
        return

    product_ids = set()
    parsed_logs = []
    for log in candidates:
        if log['id'] in existing_service_log_ids:
            continue
        match = PRODUCT_SALE_LOG_PATTERN.match((log['description'] or '').strip())
        if not match:
            continue
        product_id = int(match.group('product_id'))
        quantity = int(match.group('qty'))
        if quantity <= 0:
            continue
        parsed_logs.append((log, product_id, quantity))
        product_ids.add(product_id)

    if not parsed_logs:
        return

    products = Product.objects.in_bulk(product_ids)
    rows = []
    for log, product_id, quantity in parsed_logs:
        product = products.get(product_id)
        if not product:
            continue

        line_total = log['part_cost'] or Decimal('0.00')
        qty_decimal = Decimal(quantity)
        unit_price = (line_total / qty_decimal) if quantity else Decimal('0.00')
        cost_price = product.cost_price or Decimal('0.00')
        line_cost = cost_price * qty_decimal
        line_profit = line_total - line_cost

        rows.append(
            ProductSale(
                job_ticket_id=log['job_ticket_id'],
                product_id=product_id,
                service_log_id=log['id'],
                quantity=quantity,
                unit_price=unit_price,
                cost_price=cost_price,
                line_total=line_total,
                line_cost=line_cost,
                line_profit=line_profit,
                sold_at=log['created_at'],
            )
        )

    if rows:
        ProductSale.objects.bulk_create(rows)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0032_product_cost_price_productsale'),
    ]

    operations = [
        migrations.RunPython(backfill_product_sales, noop_reverse),
    ]
