# Generated by Django 6.0.2 on 2026-02-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0034_inventoryparty_inventoryentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobFieldPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(choices=[('device_type', 'Device Type'), ('device_brand', 'Device Brand'), ('reported_issue', 'Reported Issue'), ('additional_items', 'Additional Items')], db_index=True, max_length=32)),
                ('value', models.CharField(max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['field_name', 'sort_order', 'value'],
                'unique_together': {('field_name', 'value')},
            },
        ),
    ]
