# Generated by Django 6.0.2 on 2026-02-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0036_seed_jobfieldpreset_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryentry',
            name='invoice_number',
            field=models.CharField(
                blank=True,
                help_text='Supplier/customer invoice number for reference.',
                max_length=50,
                null=True,
            ),
        ),
    ]

