# Generated by Django 6.0.2 on 2026-02-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0037_inventoryentry_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='sales_invoice_next_number',
            field=models.PositiveIntegerField(default=1, help_text='Next sequence number to use for auto-generated sales invoices.'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='sales_invoice_prefix',
            field=models.CharField(blank=True, default='INV', help_text='Prefix for auto-generated sales invoice numbers.', max_length=20),
        ),
    ]
