# Generated by Django 6.0.2 on 2026-02-24 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0038_companyprofile_sales_invoice_next_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryentry',
            name='job_ticket',
            field=models.ForeignKey(blank=True, help_text='Linked job ticket when this sale entry is generated from job billing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_entries', to='job_tickets.jobticket'),
        ),
        migrations.AddField(
            model_name='productsale',
            name='inventory_entry',
            field=models.OneToOneField(blank=True, help_text='Linked inventory sales register entry for this job product sale.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_sale_entry', to='job_tickets.inventoryentry'),
        ),
    ]
