# Generated by Django 6.0.2 on 2026-03-01 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0039_inventoryentry_job_ticket_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppIntegrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bridge_base_url', models.URLField(default='http://127.0.0.1:3001', help_text='Base URL of the local WhatsApp bridge service.')),
                ('is_enabled', models.BooleanField(default=False, help_text='Enable automatic WhatsApp notifications for ticket events.')),
                ('default_country_code', models.CharField(default='91', help_text='Used when a customer phone number has no country code.', max_length=5)),
                ('notify_on_created', models.BooleanField(default=True)),
                ('notify_on_completed', models.BooleanField(default=True)),
                ('notify_on_delivered', models.BooleanField(default=True)),
                ('created_template', models.TextField(default='Hello {customer_name}, your ticket {job_code} has been created.\nDevice: {device_type}\nIssue: {reported_issue}\nStatus: {status}')),
                ('completed_template', models.TextField(default='Hello {customer_name}, your ticket {job_code} is completed.\nDevice: {device_type}\nStatus: {status}')),
                ('delivered_template', models.TextField(default='Hello {customer_name}, your ticket {job_code} has been delivered/closed.\nThank you for choosing us.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Integration Settings',
                'verbose_name_plural': 'WhatsApp Integration Settings',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('completed', 'Completed'), ('delivered', 'Delivered')], max_length=20)),
                ('target_phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('was_successful', models.BooleanField(default=False)),
                ('response_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_notifications', to='job_tickets.jobticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
