# Generated by Django 6.0.2 on 2026-03-03 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0040_whatsappintegrationsettings_whatsappnotificationlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(db_index=True, help_text='Device type this checklist applies to (example: Laptop, Desktop, Printer).', max_length=100, unique=True)),
                ('name', models.CharField(blank=True, help_text='Optional internal name shown in admin.', max_length=120)),
                ('notes', models.TextField(blank=True, help_text='Optional guidance shown to technicians.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['device_type'],
            },
        ),
        migrations.AddField(
            model_name='jobticket',
            name='technician_checklist',
            field=models.JSONField(blank=True, default=dict, help_text='Technician checklist answers keyed by checklist field key.'),
        ),
        migrations.CreateModel(
            name='DeviceChecklistField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.SlugField(help_text='Stable key used to store this answer (example: battery_health).', max_length=64)),
                ('label', models.CharField(max_length=120)),
                ('field_type', models.CharField(choices=[('text', 'Single Line Text'), ('textarea', 'Multi Line Text'), ('number', 'Number'), ('select', 'Dropdown Select')], default='text', max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('placeholder', models.CharField(blank=True, max_length=150)),
                ('help_text', models.CharField(blank=True, max_length=255)),
                ('options', models.TextField(blank=True, help_text='For dropdown fields, enter one option per line.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='job_tickets.devicechecklisttemplate')),
            ],
            options={
                'ordering': ['sort_order', 'label'],
                'unique_together': {('template', 'field_key')},
            },
        ),
    ]
