# Generated by Django 6.0.2 on 2026-03-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0041_devicechecklisttemplate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicechecklistfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Single Line Text'), ('textarea', 'Multi Line Text'), ('number', 'Number'), ('select', 'Dropdown Select'), ('checkbox', 'Checkbox')], default='text', max_length=20),
        ),
    ]
