# Generated by Codex on 2026-03-03

from django.db import migrations


def _options(*values):
    return "\n".join(values)


TEMPLATES = [
    {
        "device_type": "Laptop",
        "name": "Laptop Inspection Checklist",
        "notes": "Full hardware and condition check before completion.",
        "fields": [
            {"field_key": "battery_health", "label": "Battery Health", "field_type": "text", "is_required": True, "placeholder": "Example: 82% / Good / Replace soon"},
            {"field_key": "cpu_spec", "label": "CPU", "field_type": "text", "is_required": True, "placeholder": "Example: Intel i5 11th Gen"},
            {"field_key": "ram_gb", "label": "RAM (GB)", "field_type": "number", "is_required": True, "placeholder": "Example: 8"},
            {"field_key": "ssd_gb", "label": "SSD (GB)", "field_type": "number", "is_required": True, "placeholder": "Use 0 if not present"},
            {"field_key": "hdd_gb", "label": "HDD (GB)", "field_type": "number", "is_required": True, "placeholder": "Use 0 if not present"},
            {"field_key": "ports_condition", "label": "Ports Condition", "field_type": "select", "is_required": True, "options": _options("Good", "Issue Found", "Not Tested"), "help_text": "USB/Type-C/HDMI/Audio"},
            {"field_key": "speaker_condition", "label": "Speaker Condition", "field_type": "select", "is_required": True, "options": _options("Good", "Issue Found", "Not Tested")},
            {"field_key": "body_condition", "label": "Body Condition", "field_type": "select", "is_required": True, "options": _options("Good", "Minor Damage", "Major Damage")},
            {"field_key": "screen_condition", "label": "Screen Condition", "field_type": "select", "is_required": True, "options": _options("Good", "Minor Issue", "Major Issue")},
            {"field_key": "keyboard_condition", "label": "Keyboard Condition", "field_type": "select", "is_required": True, "options": _options("Good", "Issue Found", "Not Tested")},
            {"field_key": "touchpad_condition", "label": "Touchpad Condition", "field_type": "select", "is_required": True, "options": _options("Good", "Issue Found", "Not Tested")},
            {"field_key": "hinges_condition", "label": "Hinges Condition", "field_type": "select", "is_required": True, "options": _options("Good", "Loose", "Broken")},
            {"field_key": "all_tests_verified", "label": "All Physical Tests Verified", "field_type": "checkbox", "is_required": True, "help_text": "Must be checked before marking Completed."},
        ],
    },
    {
        "device_type": "Desktop",
        "name": "Desktop Inspection Checklist",
        "notes": "Desktop hardware and condition checks before completion.",
        "fields": [
            {"field_key": "cabinet_condition", "label": "Cabinet Condition", "field_type": "select", "is_required": True, "options": _options("Good", "Minor Damage", "Major Damage")},
            {"field_key": "power_supply_status", "label": "Power Supply Status", "field_type": "select", "is_required": True, "options": _options("Working", "Issue Found", "Not Tested")},
            {"field_key": "display_output_status", "label": "Display Output Status", "field_type": "select", "is_required": True, "options": _options("Good", "Issue Found", "Not Tested")},
            {"field_key": "usb_ports_status", "label": "USB Ports Status", "field_type": "select", "is_required": True, "options": _options("Good", "Issue Found", "Not Tested")},
            {"field_key": "audio_output_status", "label": "Audio Output Status", "field_type": "select", "is_required": True, "options": _options("Good", "Issue Found", "Not Tested")},
            {"field_key": "lan_port_status", "label": "LAN Port Status", "field_type": "select", "is_required": True, "options": _options("Good", "Issue Found", "Not Tested")},
            {"field_key": "cpu_spec", "label": "CPU", "field_type": "text", "is_required": True, "placeholder": "Example: Ryzen 5 5600G"},
            {"field_key": "ram_gb", "label": "RAM (GB)", "field_type": "number", "is_required": True, "placeholder": "Example: 16"},
            {"field_key": "ssd_gb", "label": "SSD (GB)", "field_type": "number", "is_required": True, "placeholder": "Use 0 if not present"},
            {"field_key": "hdd_gb", "label": "HDD (GB)", "field_type": "number", "is_required": True, "placeholder": "Use 0 if not present"},
            {"field_key": "all_tests_verified", "label": "All Physical Tests Verified", "field_type": "checkbox", "is_required": True, "help_text": "Must be checked before marking Completed."},
        ],
    },
    {
        "device_type": "Printer",
        "name": "Printer Inspection Checklist",
        "notes": "Printer condition and print-quality checks before completion.",
        "fields": [
            {"field_key": "power_on_status", "label": "Power On Status", "field_type": "select", "is_required": True, "options": _options("Working", "Issue Found", "Not Tested")},
            {"field_key": "print_quality", "label": "Print Quality", "field_type": "select", "is_required": True, "options": _options("Good", "Average", "Poor")},
            {"field_key": "paper_feed_status", "label": "Paper Feed Status", "field_type": "select", "is_required": True, "options": _options("Good", "Issue Found", "Not Tested")},
            {"field_key": "roller_condition", "label": "Roller Condition", "field_type": "select", "is_required": True, "options": _options("Good", "Worn", "Replace")},
            {"field_key": "usb_lan_port_status", "label": "USB/LAN Port Status", "field_type": "select", "is_required": True, "options": _options("Good", "Issue Found", "Not Tested")},
            {"field_key": "cartridge_toner_level", "label": "Cartridge/Toner Level", "field_type": "text", "is_required": True, "placeholder": "Example: 60%"},
            {"field_key": "page_counter", "label": "Page Counter", "field_type": "number", "is_required": False, "placeholder": "Optional"},
            {"field_key": "test_page_printed", "label": "Test Page Printed", "field_type": "checkbox", "is_required": True, "help_text": "Must be checked before marking Completed."},
        ],
    },
]


def seed_device_checklist_templates(apps, schema_editor):
    DeviceChecklistTemplate = apps.get_model("job_tickets", "DeviceChecklistTemplate")
    DeviceChecklistField = apps.get_model("job_tickets", "DeviceChecklistField")

    for template_data in TEMPLATES:
        device_type = template_data["device_type"]
        if DeviceChecklistTemplate.objects.filter(device_type__iexact=device_type).exists():
            continue

        template = DeviceChecklistTemplate.objects.create(
            device_type=device_type,
            name=template_data.get("name", ""),
            notes=template_data.get("notes", ""),
            is_active=True,
        )

        for index, field_data in enumerate(template_data.get("fields", []), start=1):
            DeviceChecklistField.objects.create(
                template=template,
                field_key=field_data["field_key"],
                label=field_data["label"],
                field_type=field_data.get("field_type", "text"),
                is_required=bool(field_data.get("is_required", False)),
                placeholder=field_data.get("placeholder", ""),
                help_text=field_data.get("help_text", ""),
                options=field_data.get("options", ""),
                sort_order=index * 10,
                is_active=True,
            )


class Migration(migrations.Migration):

    dependencies = [
        ("job_tickets", "0042_alter_devicechecklistfield_field_type"),
    ]

    operations = [
        migrations.RunPython(seed_device_checklist_templates, migrations.RunPython.noop),
    ]
