# Generated by Django 4.2 on 2026-03-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0044_inventorybill_inventoryentry_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reserved_stock',
            field=models.PositiveIntegerField(default=0, help_text='Minimum quantity to keep in stock for essential/reserved items.'),
        ),
    ]
