# Generated by Django 6.0.2 on 2026-03-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0045_product_reserved_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappintegrationsettings',
            name='public_site_url',
            field=models.URLField(
                default='http://127.0.0.1:8000',
                help_text='Public base URL used for client status/receipt links sent on WhatsApp.',
            ),
        ),
    ]

