# Generated by Django 6.0.2 on 2026-03-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0046_whatsappintegrationsettings_public_site_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappintegrationsettings',
            name='created_pdf_caption_template',
            field=models.TextField(
                blank=True,
                default='Job Ticket {job_code}',
                help_text='Caption used when sending the job ticket PDF on creation.',
            ),
        ),
    ]

