# Generated by Django 5.2.5 on 2026-03-13 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0047_whatsappintegrationsettings_created_pdf_caption_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTicketPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='job_ticket_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('job_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='job_tickets.jobticket')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
