# Generated by Django 4.2 on 2026-03-14 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0048_jobticketphoto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyprofile',
            options={'permissions': [('view_financial_reports', 'Can view financial reports')], 'verbose_name': 'Company Profile', 'verbose_name_plural': 'Company Profile'},
        ),
        migrations.AlterField(
            model_name='whatsappintegrationsettings',
            name='completed_template',
            field=models.TextField(default='Hello {customer_name}, your ticket {job_code} is completed.\nDevice: {device_brand} {device_model} ({device_type})\nStatus: {status}\nTrack status: {status_link}'),
        ),
        migrations.AlterField(
            model_name='whatsappintegrationsettings',
            name='created_template',
            field=models.TextField(default='Hello {customer_name}, your ticket {job_code} has been created.\nDevice: {device_type} - {device_brand} {device_model}\nIssue: {reported_issue}\nStatus: {status}\nWe have attached your job ticket PDF.'),
        ),
        migrations.AlterField(
            model_name='whatsappintegrationsettings',
            name='delivered_template',
            field=models.TextField(default="Hello {customer_name}, your ticket {job_code} is now closed.\nWe hope you're happy with the service.\nPlease share your feedback here: {status_link}"),
        ),
    ]
