# Generated by Django 4.2 on 2026-03-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0049_alter_companyprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobticket',
            name='feedback_rating',
            field=models.IntegerField(
                blank=True,
                null=True,
                choices=[
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                ],
                help_text='Customer rating (1-10)',
            ),
        ),
    ]
