# Generated by Django 4.2 on 2026-03-24 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_tickets', '0051_jobticketphoto_db_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSessionActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('channel', models.CharField(choices=[('web', 'Web'), ('admin', 'Admin'), ('api', 'API')], default='web', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('logged_out', 'Logged Out'), ('expired', 'Expired')], db_index=True, default='active', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('login_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_activity_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_activity_path', models.CharField(blank=True, max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('logout_at', models.DateTimeField(blank=True, null=True)),
                ('logout_reason', models.CharField(blank=True, max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Session Activity',
                'verbose_name_plural': 'User Session Activities',
                'ordering': ['-login_at'],
            },
        ),
        migrations.AddIndex(
            model_name='usersessionactivity',
            index=models.Index(fields=['user', 'status'], name='job_tickets_user_id_7a1b66_idx'),
        ),
        migrations.AddIndex(
            model_name='usersessionactivity',
            index=models.Index(fields=['user', '-login_at'], name='job_tickets_user_id_fda464_idx'),
        ),
    ]
