# Generated by Django 4.2 on 2026-04-01 17:37

from django.db import migrations, models
import job_tickets.gst_utils


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0052_usersessionactivity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='annual_turnover_band',
            field=models.CharField(choices=[('up_to_5cr', 'Up to Rs. 5 Cr'), ('5_to_10cr', 'Rs. 5 Cr to 10 Cr'), ('above_10cr', 'Above Rs. 10 Cr')], default='up_to_5cr', max_length=20),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='default_place_of_supply_state',
            field=models.CharField(blank=True, help_text='Default place of supply state code used for billing.', max_length=2, validators=[job_tickets.gst_utils.validate_state_code]),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='e_invoice_applicable',
            field=models.BooleanField(default=False, help_text='Whether e-invoice compliance applies to this business.'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='e_way_bill_enabled',
            field=models.BooleanField(default=True, help_text='Enable e-Way Bill related workflow fields.'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='filing_frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='legal_name',
            field=models.CharField(blank=True, help_text='Registered legal name used on GST documents.', max_length=200),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='lut_bond_enabled',
            field=models.BooleanField(default=False, help_text='Use LUT/Bond for eligible zero-rated supplies.'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='qrmp_enabled',
            field=models.BooleanField(default=False, help_text='Enable quarterly return filing under QRMP.'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='registration_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('composition', 'Composition'), ('unregistered', 'Unregistered')], default='regular', max_length=20),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='state_code',
            field=models.CharField(blank=True, help_text='2-digit GST state code of the business registration.', max_length=2, validators=[job_tickets.gst_utils.validate_state_code]),
        ),
        migrations.AddField(
            model_name='inventoryparty',
            name='contact_person',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='inventoryparty',
            name='country',
            field=models.CharField(blank=True, default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='inventoryparty',
            name='default_place_of_supply_state',
            field=models.CharField(blank=True, help_text='Optional default place of supply state code for billing.', max_length=2, validators=[job_tickets.gst_utils.validate_state_code]),
        ),
        migrations.AddField(
            model_name='inventoryparty',
            name='gst_registration_type',
            field=models.CharField(choices=[('registered', 'Registered'), ('unregistered', 'Unregistered'), ('composition', 'Composition'), ('consumer', 'Consumer'), ('sez', 'SEZ'), ('overseas', 'Overseas')], default='unregistered', max_length=20),
        ),
        migrations.AddField(
            model_name='inventoryparty',
            name='legal_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='inventoryparty',
            name='shipping_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inventoryparty',
            name='state_code',
            field=models.CharField(blank=True, help_text='2-digit GST state code.', max_length=2, validators=[job_tickets.gst_utils.validate_state_code]),
        ),
        migrations.AddField(
            model_name='product',
            name='cess_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Default cess rate, if applicable.', max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=18, help_text='Default GST rate for this product or service.', max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='hsn_sac_code',
            field=models.CharField(blank=True, help_text='HSN for goods or SAC for services.', max_length=8, validators=[job_tickets.gst_utils.validate_hsn_sac_code]),
        ),
        migrations.AddField(
            model_name='product',
            name='is_tax_inclusive_default',
            field=models.BooleanField(default=False, help_text='Treat entered prices as tax-inclusive by default for this item.'),
        ),
        migrations.AddField(
            model_name='product',
            name='item_type',
            field=models.CharField(choices=[('goods', 'Goods'), ('service', 'Service')], default='goods', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_category',
            field=models.CharField(choices=[('taxable', 'Taxable'), ('exempt', 'Exempt'), ('nil_rated', 'Nil Rated'), ('non_gst', 'Non-GST')], default='taxable', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='uqc',
            field=models.CharField(blank=True, help_text='Unit Quantity Code used in GST summaries, for example NOS or KGS.', max_length=20),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='gstin',
            field=models.CharField(blank=True, help_text='GST Identification Number', max_length=15, validators=[job_tickets.gst_utils.validate_gstin]),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='pan',
            field=models.CharField(blank=True, help_text='PAN Number', max_length=10, validators=[job_tickets.gst_utils.validate_pan]),
        ),
        migrations.AlterField(
            model_name='inventoryparty',
            name='gstin',
            field=models.CharField(blank=True, help_text='GSTIN for B2B transactions.', max_length=15, validators=[job_tickets.gst_utils.validate_gstin]),
        ),
        migrations.AlterField(
            model_name='inventoryparty',
            name='pan',
            field=models.CharField(blank=True, max_length=10, validators=[job_tickets.gst_utils.validate_pan]),
        ),
    ]
