# Generated by Django 4.2 on 2026-04-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0053_companyprofile_annual_turnover_band_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobticket',
            name='requires_laptop_inspection_checklist',
            field=models.BooleanField(default=False, help_text='When enabled for laptop jobs, the technician must complete the inspection checklist before marking the ticket completed.'),
        ),
    ]
