# Generated by Django 6.0.4 on 2026-04-16 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0055_alter_product_stock_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappnotificationlog',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('completed', 'Completed'), ('delivered', 'Delivered'), ('manual', 'Manual')], max_length=20),
        ),
        migrations.CreateModel(
            name='MessageQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp')], db_index=True, default='whatsapp', max_length=20)),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('completed', 'Completed'), ('delivered', 'Delivered'), ('manual', 'Manual')], db_index=True, default='manual', max_length=20)),
                ('target_phone', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True)),
                ('pdf_url', models.URLField(blank=True)),
                ('caption', models.TextField(blank=True)),
                ('filename', models.CharField(blank=True, default='job-ticket.pdf', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('transport', models.CharField(blank=True, default='electron-whatsapp-bridge', max_length=50)),
                ('bridge_message_id', models.CharField(blank=True, max_length=255)),
                ('bridge_status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_queues', to='job_tickets.jobticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='whatsappnotificationlog',
            name='message_queue',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_log', to='job_tickets.messagequeue'),
        ),
    ]
