# Generated by Django 6.0.4 on 2026-04-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0056_alter_whatsappnotificationlog_event_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappintegrationsettings',
            name='bridge_base_url',
        ),
        migrations.AddField(
            model_name='whatsappintegrationsettings',
            name='access_token',
            field=models.TextField(blank=True, help_text='Permanent access token used to call the WhatsApp Cloud API.'),
        ),
        migrations.AddField(
            model_name='whatsappintegrationsettings',
            name='api_version',
            field=models.CharField(default='v23.0', help_text='Graph API version used for WhatsApp Cloud API requests.', max_length=16),
        ),
        migrations.AddField(
            model_name='whatsappintegrationsettings',
            name='app_secret',
            field=models.CharField(blank=True, help_text='Optional Meta app secret used to validate webhook signatures.', max_length=255),
        ),
        migrations.AddField(
            model_name='whatsappintegrationsettings',
            name='completed_template_name',
            field=models.CharField(blank=True, help_text='Approved template name used for the ticket completed notification.', max_length=100),
        ),
        migrations.AddField(
            model_name='whatsappintegrationsettings',
            name='created_template_name',
            field=models.CharField(blank=True, help_text='Approved template name used for the ticket created notification.', max_length=100),
        ),
        migrations.AddField(
            model_name='whatsappintegrationsettings',
            name='delivered_template_name',
            field=models.CharField(blank=True, help_text='Approved template name used for the ticket delivered/closed notification.', max_length=100),
        ),
        migrations.AddField(
            model_name='whatsappintegrationsettings',
            name='phone_number_id',
            field=models.CharField(blank=True, help_text='Phone Number ID from Meta WhatsApp Manager / API Setup.', max_length=64),
        ),
        migrations.AddField(
            model_name='whatsappintegrationsettings',
            name='template_language_code',
            field=models.CharField(default='en_US', help_text='Language code used for approved template messages (example: en_US).', max_length=20),
        ),
        migrations.AddField(
            model_name='whatsappintegrationsettings',
            name='test_template_name',
            field=models.CharField(blank=True, default='hello_world', help_text='Approved template name used for manual Cloud API test sends.', max_length=100),
        ),
        migrations.AddField(
            model_name='whatsappintegrationsettings',
            name='webhook_verify_token',
            field=models.CharField(blank=True, help_text='Custom verify token used while configuring the Meta webhook.', max_length=255),
        ),
        migrations.AlterField(
            model_name='messagequeue',
            name='transport',
            field=models.CharField(blank=True, default='whatsapp-cloud-api', max_length=50),
        ),
        migrations.AlterField(
            model_name='whatsappintegrationsettings',
            name='created_template',
            field=models.TextField(default='Hello {customer_name}, your ticket {job_code} has been created.\nDevice: {device_type} - {device_brand} {device_model}\nIssue: {reported_issue}\nStatus: {status}\nReceipt: {receipt_link}'),
        ),
    ]
