# Generated by Django 6.0.4 on 2026-04-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0057_remove_whatsappintegrationsettings_bridge_base_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappintegrationsettings',
            name='public_site_url',
            field=models.URLField(default='http://192.168.1.4:8000', help_text='Public base URL used for client status/receipt links sent on WhatsApp.'),
        ),
    ]
