# Generated by Codex on 2026-05-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0058_alter_whatsappintegrationsettings_public_site_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappintegrationsettings',
            name='delivery_method',
            field=models.CharField(
                choices=[
                    ('cloud_api', 'WhatsApp Cloud API'),
                    ('bridge', 'WhatsApp Bridge (QR Login)'),
                ],
                default='cloud_api',
                help_text='Choose how automatic WhatsApp notifications are sent.',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='whatsappintegrationsettings',
            name='bridge_base_url',
            field=models.URLField(
                default='http://127.0.0.1:3001',
                help_text='Base URL of the local WhatsApp bridge service used for QR login delivery.',
            ),
        ),
    ]
