# Generated by Django 6.0.4 on 2026-05-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0059_whatsappintegrationsettings_bridge_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='specializedservice',
            name='vendor_balance_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Remaining amount payable to the vendor after discount and paid amount.', max_digits=10),
        ),
        migrations.AddField(
            model_name='specializedservice',
            name='vendor_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount or adjustment received from the vendor.', max_digits=10),
        ),
        migrations.AddField(
            model_name='specializedservice',
            name='vendor_paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount already paid to the vendor.', max_digits=10),
        ),
    ]
