# Generated by Django 6.0.4 on 2026-05-03 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0061_vendorpayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobticket',
            name='estimation_note',
            field=models.TextField(blank=True, help_text='Customer-facing estimation/callback note.'),
        ),
        migrations.CreateModel(
            name='JobReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_at', models.DateTimeField(db_index=True)),
                ('purpose', models.CharField(default='Customer callback', max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('last_prompted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_reminders', to=settings.AUTH_USER_MODEL)),
                ('job_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='job_tickets.jobticket')),
            ],
            options={
                'ordering': ['due_at', 'id'],
                'indexes': [models.Index(fields=['status', 'due_at'], name='job_tickets_status_8f2f12_idx')],
            },
        ),
    ]
