# Generated by Django 6.0.4 on 2026-05-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0062_jobticket_estimation_note_jobreminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappintegrationsettings',
            name='estimate_template',
            field=models.TextField(default='Hello {customer_name}, estimate for ticket {job_code} is {estimated_amount}.\nDevice: {device_brand} {device_model} ({device_type})\nNote: {estimation_note}\nStatus: {status}\nTrack status: {status_link}'),
        ),
        migrations.AddField(
            model_name='whatsappintegrationsettings',
            name='estimate_template_name',
            field=models.CharField(blank=True, help_text='Approved template name used for manual estimate messages.', max_length=100),
        ),
        migrations.AlterField(
            model_name='messagequeue',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('completed', 'Completed'), ('delivered', 'Delivered'), ('estimate', 'Estimate'), ('manual', 'Manual')], db_index=True, default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='whatsappnotificationlog',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('completed', 'Completed'), ('delivered', 'Delivered'), ('estimate', 'Estimate'), ('manual', 'Manual')], max_length=20),
        ),
    ]
