# Generated by Django 6.0.4 on 2026-05-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0063_whatsappintegrationsettings_estimate_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobticket',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
