# Generated by Django 6.0.4 on 2026-05-04 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_feedback_due_dates(apps, schema_editor):
    JobTicket = apps.get_model('job_tickets', 'JobTicket')
    JobTicket.objects.filter(
        feedback_rating__isnull=False,
    ).exclude(
        feedback_followup_status='received',
    ).update(
        feedback_followup_status='received',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0064_jobticket_closed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobticket',
            name='feedback_due_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When the post-service feedback follow-up becomes due.', null=True),
        ),
        migrations.AddField(
            model_name='jobticket',
            name='feedback_followup_called_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobticket',
            name='feedback_followup_marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_feedback_followups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobticket',
            name='feedback_followup_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobticket',
            name='feedback_followup_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('message_sent', 'Message Sent'), ('received', 'Feedback Received'), ('called_happy', 'Called - Happy'), ('called_issue', 'Called - Issue'), ('no_answer', 'No Answer'), ('call_later', 'Call Later')], db_index=True, default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='jobticket',
            name='feedback_message_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the 7-day feedback WhatsApp was queued/sent.', null=True),
        ),
        migrations.AddField(
            model_name='whatsappintegrationsettings',
            name='feedback_template',
            field=models.TextField(blank=True, default='Hello {customer_name}, your ticket {job_code} was closed 7 days ago.\nPlease share your service feedback here: {status_link}'),
        ),
        migrations.AddField(
            model_name='whatsappintegrationsettings',
            name='feedback_template_name',
            field=models.CharField(blank=True, help_text='Approved template name used for 7-day feedback follow-up messages.', max_length=100),
        ),
        migrations.AddField(
            model_name='whatsappintegrationsettings',
            name='notify_on_feedback',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='messagequeue',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('completed', 'Completed'), ('delivered', 'Delivered'), ('estimate', 'Estimate'), ('feedback', 'Feedback'), ('manual', 'Manual')], db_index=True, default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='whatsappnotificationlog',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('completed', 'Completed'), ('delivered', 'Delivered'), ('estimate', 'Estimate'), ('feedback', 'Feedback'), ('manual', 'Manual')], max_length=20),
        ),
        migrations.RunPython(seed_feedback_due_dates, migrations.RunPython.noop),
    ]
