# Generated by Django 6.0.4 on 2026-05-05 12:38

from django.db import migrations


def clear_historical_feedback_followups(apps, schema_editor):
    JobTicket = apps.get_model('job_tickets', 'JobTicket')
    JobTicket.objects.filter(
        status='Closed',
        feedback_rating__isnull=True,
    ).update(
        feedback_due_at=None,
        feedback_message_sent_at=None,
        feedback_followup_status='pending',
        feedback_followup_called_at=None,
        feedback_followup_marked_by=None,
        feedback_followup_note='',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0065_jobticket_feedback_due_at_and_more'),
    ]

    operations = [
        migrations.RunPython(clear_historical_feedback_followups, migrations.RunPython.noop),
    ]
