# Generated by Django 6.0.4 on 2026-05-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0066_clear_historical_feedback_followups'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobticket',
            name='feedback_followup_enabled',
            field=models.BooleanField(db_index=True, default=False, help_text='Enabled when this job should enter the 7-day feedback follow-up queue.'),
        ),
    ]
