# Generated by Django 6.0.4 on 2026-05-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0068_inventorycreditpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorybill',
            name='invoice_date',
            field=models.DateField(blank=True, help_text='Original supplier/customer invoice date when different from entry date.', null=True),
        ),
    ]
