# Generated by Django 4.2.7 on 2026-05-25 07:07

from django.db import migrations, models
import django.db.models.deletion


def backfill_default_workspace(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    CompanyWorkspace = apps.get_model('job_tickets', 'CompanyWorkspace')
    CompanyUserMembership = apps.get_model('job_tickets', 'CompanyUserMembership')
    CompanyProfile = apps.get_model('job_tickets', 'CompanyProfile')
    TechnicianProfile = apps.get_model('job_tickets', 'TechnicianProfile')

    owner = (
        User.objects.filter(is_superuser=True).order_by('id').first()
        or User.objects.filter(is_staff=True).order_by('id').first()
        or User.objects.order_by('id').first()
    )
    if not owner:
        return

    profile = CompanyProfile.objects.order_by('id').first()
    workspace_name = getattr(profile, 'company_name', '') or 'Default Workspace'
    workspace, _ = CompanyWorkspace.objects.get_or_create(
        slug='default-workspace',
        defaults={
            'name': workspace_name,
            'owner': owner,
            'contact_email': getattr(owner, 'email', '') or '',
            'status': 'active',
        },
    )

    if profile and not profile.workspace_id:
        profile.workspace_id = workspace.id
        profile.save(update_fields=['workspace'])

    scoped_models = [
        'Client',
        'DeviceChecklistTemplate',
        'InventoryBill',
        'InventoryCreditPayment',
        'InventoryEntry',
        'InventoryParty',
        'JobFieldPreset',
        'JobTicket',
        'Product',
        'ProductSale',
        'TechnicianProfile',
        'Vendor',
        'WhatsAppIntegrationSettings',
    ]
    for model_name in scoped_models:
        model = apps.get_model('job_tickets', model_name)
        model.objects.filter(workspace__isnull=True).update(workspace=workspace)

    staff_users = User.objects.filter(is_staff=True)
    technician_user_ids = set(TechnicianProfile.objects.values_list('user_id', flat=True))
    for user in User.objects.filter(id__in=set(staff_users.values_list('id', flat=True)) | technician_user_ids):
        if user.id == owner.id:
            role = 'owner'
        elif user.id in technician_user_ids and not user.is_staff:
            role = 'technician'
        else:
            role = 'staff'
        CompanyUserMembership.objects.get_or_create(
            workspace=workspace,
            user=user,
            defaults={'role': role},
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0070_companyworkspace_companyusermembership'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobfieldpreset',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='client',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='job_tickets.companyworkspace'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_profiles', to='job_tickets.companyworkspace'),
        ),
        migrations.AddField(
            model_name='devicechecklisttemplate',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_checklist_templates', to='job_tickets.companyworkspace'),
        ),
        migrations.AddField(
            model_name='inventorybill',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_bills', to='job_tickets.companyworkspace'),
        ),
        migrations.AddField(
            model_name='inventorycreditpayment',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_credit_payments', to='job_tickets.companyworkspace'),
        ),
        migrations.AddField(
            model_name='inventoryentry',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_entries', to='job_tickets.companyworkspace'),
        ),
        migrations.AddField(
            model_name='inventoryparty',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_parties', to='job_tickets.companyworkspace'),
        ),
        migrations.AddField(
            model_name='jobfieldpreset',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_field_presets', to='job_tickets.companyworkspace'),
        ),
        migrations.AddField(
            model_name='jobticket',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_tickets', to='job_tickets.companyworkspace'),
        ),
        migrations.AddField(
            model_name='product',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='job_tickets.companyworkspace'),
        ),
        migrations.AddField(
            model_name='productsale',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_sales', to='job_tickets.companyworkspace'),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technicians', to='job_tickets.companyworkspace'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='job_tickets.companyworkspace'),
        ),
        migrations.AddField(
            model_name='whatsappintegrationsettings',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_settings', to='job_tickets.companyworkspace'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='devicechecklisttemplate',
            name='device_type',
            field=models.CharField(db_index=True, help_text='Device type this checklist applies to (example: Laptop, Desktop, Printer).', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='company_name',
            field=models.CharField(help_text='The official name of the vendor company.', max_length=255),
        ),
        migrations.RunPython(backfill_default_workspace, noop_reverse),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('workspace', 'phone'), name='unique_client_phone_per_workspace'),
        ),
        migrations.AddConstraint(
            model_name='devicechecklisttemplate',
            constraint=models.UniqueConstraint(fields=('workspace', 'device_type'), name='unique_checklist_template_per_workspace'),
        ),
        migrations.AddConstraint(
            model_name='jobfieldpreset',
            constraint=models.UniqueConstraint(fields=('workspace', 'field_name', 'value'), name='unique_job_preset_per_workspace'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('workspace', 'sku'), name='unique_product_sku_per_workspace'),
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.UniqueConstraint(fields=('workspace', 'company_name'), name='unique_vendor_company_per_workspace'),
        ),
    ]
