# Generated by Django 4.2.7 on 2026-08-19 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0074_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='client',
            name='client_phone_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventoryentry',
            name='ie_type_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventoryentry',
            name='ie_party_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='jobreminder',
            name='jr_status_due_idx',
        ),
        migrations.RemoveIndex(
            model_name='jobticket',
            name='jt_status_updated_idx',
        ),
        migrations.RemoveIndex(
            model_name='jobticket',
            name='jt_status_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='jobticket',
            name='jt_workspace_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='jobticket',
            name='jt_customer_phone_idx',
        ),
        migrations.RemoveIndex(
            model_name='jobticket',
            name='jt_closed_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='jobticketlog',
            name='jtl_ticket_action_idx',
        ),
        migrations.RemoveIndex(
            model_name='servicelog',
            name='sl_job_ticket_idx',
        ),
        migrations.RemoveIndex(
            model_name='specializedservice',
            name='ss_status_returned_idx',
        ),
    ]
