# Generated by Django 5.2.17 on 2026-09-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0075_remove_client_client_phone_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_key', models.CharField(max_length=180, unique=True)),
                ('last_counter', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sequence_key'],
            },
        ),
    ]
