# Generated by Django 5.2.17 on 2026-09-14 06:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0076_inventorynumbersequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorybill',
            name='is_reversed',
            field=models.BooleanField(db_index=True, default=False, help_text='True when this bill has been formally reversed. A reversed bill cannot be reversed again.'),
        ),
        migrations.AddField(
            model_name='inventorybill',
            name='reversal_note',
            field=models.TextField(blank=True, help_text='Reason recorded at the time of reversal.'),
        ),
        migrations.AddField(
            model_name='inventorybill',
            name='reversal_of',
            field=models.ForeignKey(blank=True, help_text='Points to the original bill this bill was created to reverse.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversal_bills', to='job_tickets.inventorybill'),
        ),
        migrations.AddField(
            model_name='inventorybill',
            name='reversed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the original bill was marked as reversed.', null=True),
        ),
        migrations.AddField(
            model_name='inventorybill',
            name='reversed_by',
            field=models.ForeignKey(blank=True, help_text='User who performed the reversal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_inventory_bills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorybill',
            name='source_bill',
            field=models.ForeignKey(blank=True, help_text='For purchase_return and sale_return bills: the original purchase/sale bill this return is against. Used to compute vendor credits and customer refunds.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_bills', to='job_tickets.inventorybill'),
        ),
        migrations.CreateModel(
            name='InventoryBillLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('BILL_CREATED', 'Bill Created'), ('BILL_EDITED', 'Bill Edited'), ('BILL_REVERSED', 'Bill Reversed'), ('REVERSAL_CREATED', 'Reversal Bill Created'), ('PAYMENT_RECORDED', 'Payment Recorded'), ('RETURN_LINKED', 'Return Linked to Source Bill'), ('VENDOR_CREDIT_CREATED', 'Vendor Credit Created'), ('VENDOR_CREDIT_APPLIED', 'Vendor Credit Applied')], db_index=True, max_length=40)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('details', models.TextField(blank=True, help_text='Human-readable description of the event. Include before/after values for edits.')),
                ('bill', models.ForeignKey(help_text='The bill this log entry is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='job_tickets.inventorybill')),
                ('related_bill', models.ForeignKey(blank=True, help_text='For reversals: the reversal bill. For returns: the source bill.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_audit_logs', to='job_tickets.inventorybill')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_bill_logs', to='job_tickets.companyworkspace')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='InventoryVendorCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_amount', models.DecimalField(decimal_places=2, help_text='Total credit value (= return bill total at time of creation). Immutable after creation.', max_digits=12)),
                ('applied_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total amount of this credit that has been applied to purchase bills or refunded.', max_digits=12)),
                ('status', models.CharField(choices=[('open', 'Open'), ('partially_applied', 'Partially Applied'), ('fully_applied', 'Fully Applied'), ('voided', 'Voided')], db_index=True, default='open', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_credits_created', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(help_text='The vendor (supplier) party this credit belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='vendor_credits', to='job_tickets.inventoryparty')),
                ('return_bill', models.OneToOneField(help_text='The purchase_return bill that generated this vendor credit.', on_delete=django.db.models.deletion.CASCADE, related_name='vendor_credit', to='job_tickets.inventorybill')),
                ('source_bill', models.ForeignKey(blank=True, help_text='The original purchase bill this return is against. Null when the return is not tied to a specific bill.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_credits_from_returns', to='job_tickets.inventorybill')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_vendor_credits', to='job_tickets.companyworkspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryVendorCreditApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount of the credit applied. Cannot exceed credit balance or bill balance.', max_digits=12)),
                ('applied_date', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_credit_applications_created', to=settings.AUTH_USER_MODEL)),
                ('target_bill', models.ForeignKey(help_text='The purchase bill this credit is being applied against.', on_delete=django.db.models.deletion.CASCADE, related_name='credit_applications', to='job_tickets.inventorybill')),
                ('vendor_credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='job_tickets.inventoryvendorcredit')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_credit_applications', to='job_tickets.companyworkspace')),
            ],
            options={
                'ordering': ['-applied_date', '-created_at'],
            },
        ),
    ]
