# Generated by Django 5.2.17 on 2026-09-16 05:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0077_bill_reversal_vendor_credit_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobticket',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount collected from the customer for this job.', max_digits=12),
        ),
        migrations.AddField(
            model_name='jobticket',
            name='payment_date',
            field=models.DateTimeField(blank=True, help_text='When the payment or settlement occurred.', null=True),
        ),
        migrations.AddField(
            model_name='jobticket',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('upi', 'UPI / QR'), ('card', 'Card'), ('transfer', 'Transfer')], help_text='Payment method used for settlement.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobticket',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Transaction ID, UPI reference, or check number.', max_length=100),
        ),
        migrations.AddField(
            model_name='jobticket',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('part_paid', 'Partially Paid'), ('paid', 'Paid')], db_index=True, default='unpaid', help_text='Settlement status of this repair ticket.', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventorycreditpayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI / QR'), ('card', 'Card'), ('transfer', 'Transfer')], default='cash', max_length=20),
        ),
    ]
