# Generated by Django 5.2.17 on 2026-09-24 13:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0082_grant_task_management_access'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_number', models.CharField(blank=True, db_index=True, max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('rent', 'Rent'), ('utilities', 'Electricity & Utilities'), ('refreshments', 'Tea, Snacks & Refreshments'), ('travel', 'Travel & Conveyance'), ('tools_equipment', 'Tools & Equipment'), ('job_parts_outsource', 'Job Parts / External Lab / Outsourcing'), ('software_internet', 'Internet & Software'), ('office_supplies', 'Office & Cleaning Supplies'), ('salary_advance', 'Staff Advance / Wages'), ('maintenance', 'Shop Maintenance & Repairs'), ('other', 'Other Overhead')], db_index=True, default='other', max_length=50)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI / GPay / PhonePe'), ('bank_transfer', 'Bank Transfer / NEFT'), ('card', 'Debit / Credit Card'), ('petty_cash', 'Petty Cash'), ('other', 'Other')], default='cash', max_length=30)),
                ('expense_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('is_billable_to_customer', models.BooleanField(default=False, help_text='Whether this expense is passed on or billed to the customer.')),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='expense_receipts/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='job_tickets.jobticket')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_expenses', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='job_tickets.companyworkspace')),
            ],
            options={
                'ordering': ['-expense_date', '-id'],
                'indexes': [models.Index(fields=['workspace', 'expense_date'], name='job_tickets_workspa_a8c882_idx'), models.Index(fields=['workspace', 'category'], name='job_tickets_workspa_ccff8d_idx'), models.Index(fields=['job_ticket'], name='job_tickets_job_tic_574c94_idx')],
            },
        ),
    ]
