# Generated by Django 5.2.17 on 2026-09-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0084_grant_expense_management_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobticket',
            name='feedback_call_attempts',
            field=models.PositiveIntegerField(default=0, help_text='Number of unsuccessful call attempts (e.g. no answer).'),
        ),
        migrations.AlterField(
            model_name='jobticket',
            name='feedback_followup_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('message_sent', 'Message Sent'), ('received', 'Feedback Received'), ('called_happy', 'Called - Happy'), ('called_issue', 'Called - Issue'), ('no_answer', 'No Answer'), ('call_later', 'Call Later'), ('unreachable', 'Unreachable (3 Attempts)')], db_index=True, default='pending', max_length=30),
        ),
    ]
