# Generated by Django 5.2.17 on 2026-09-25 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0085_jobticket_feedback_call_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryentry',
            name='serial_numbers_text',
            field=models.TextField(blank=True, default='', help_text='Serial / IMEI numbers for this entry line.'),
        ),
        migrations.AddField(
            model_name='product',
            name='bin_location',
            field=models.CharField(blank=True, default='', help_text='Rack / Shelf / Bin storage location in warehouse or shop.', max_length=60),
        ),
        migrations.AddField(
            model_name='product',
            name='customer_warranty_months',
            field=models.PositiveIntegerField(default=0, help_text='Warranty period provided to customer in months.'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_serial_tracking',
            field=models.BooleanField(default=False, help_text='Enable unique Serial / IMEI tracking for this product.'),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor_warranty_months',
            field=models.PositiveIntegerField(default=0, help_text='Warranty period from supplier in months.'),
        ),
        migrations.CreateModel(
            name='ProductItemSerial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('in_stock', 'In Stock'), ('sold', 'Sold'), ('consumed_in_job', 'Consumed in Job'), ('defective_rma', 'Defective / RMA Return'), ('written_off', 'Written Off')], db_index=True, default='in_stock', max_length=25)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vendor_warranty_until', models.DateField(blank=True, null=True)),
                ('sale_date', models.DateField(blank=True, null=True)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('customer_warranty_until', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumed_serials', to='job_tickets.jobticket')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_items', to='job_tickets.product')),
                ('purchase_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inward_serials', to='job_tickets.inventoryentry')),
                ('sale_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outward_serials', to='job_tickets.inventoryentry')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_serials', to='job_tickets.companyworkspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'product', 'serial_number'), name='unique_product_serial_per_workspace')],
            },
        ),
    ]
