# Generated by Django 5.2.17 on 2026-09-27 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0086_inventoryentry_serial_numbers_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceRack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Rack / Shelf identifier (e.g., Rack A1, Shelf 2, Tray 10).', max_length=60)),
                ('group', models.CharField(default='Shop', help_text='Location group (e.g., Shop, Godown, Bench).', max_length=60)),
                ('description', models.CharField(blank=True, default='', help_text='Optional description or position note.', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive racks are hidden from intake pickers.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_racks', to='job_tickets.companyworkspace')),
            ],
            options={
                'ordering': ['group', 'name'],
                'unique_together': {('workspace', 'name', 'group')},
            },
        ),
        migrations.AddField(
            model_name='jobticket',
            name='rack',
            field=models.ForeignKey(blank=True, help_text='Assigned physical storage rack/shelf location for this device.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_tickets', to='job_tickets.devicerack'),
        ),
    ]
