# Generated by Django 5.2.17 on 2026-09-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0087_devicerack_jobticket_rack'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicerack',
            name='total_columns',
            field=models.PositiveIntegerField(default=10, help_text='Total number of numbered columns/slots in this rack.'),
        ),
        migrations.AddField(
            model_name='jobticket',
            name='rack_column',
            field=models.PositiveIntegerField(blank=True, help_text='Specific column/slot number in the storage rack.', null=True),
        ),
    ]
