# Generated by Django 5.2.17 on 2026-09-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0088_devicerack_total_columns_jobticket_rack_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobticketlog',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Job Created'), ('ASSIGNED', 'Technician Assigned'), ('STATUS', 'Status Changed'), ('NOTE', 'Note Updated'), ('SERVICE', 'Service Log Added/Updated'), ('BILLING', 'Billing Info Updated'), ('CLOSED', 'Job Closed'), ('DETAILS', 'Customer & Device Details Updated')], max_length=50),
        ),
    ]
