# Generated by Django 5.2.17 on 2026-09-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0089_alter_jobticketlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobticket',
            name='device_password',
            field=models.CharField(blank=True, help_text='Device PIN, password, or pattern for technician access.', max_length=100),
        ),
    ]
