# Generated by Django 5.2.17 on 2026-09-29 07:46

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0090_jobticket_device_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Cash in Hand, Federal Bank - Pattambi, Petty Cash', max_length=150)),
                ('account_type', models.CharField(choices=[('cash', 'Cash Drawer / In-Hand'), ('bank', 'Bank Account'), ('upi_wallet', 'UPI QR / Digital Wallet')], db_index=True, default='cash', max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=150)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('ifsc_code', models.CharField(blank=True, max_length=20)),
                ('branch', models.CharField(blank=True, max_length=150)),
                ('upi_id', models.CharField(blank=True, help_text='UPI ID or VPA for payments', max_length=100)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_default_cash', models.BooleanField(default=False, help_text='Primary account for cash collections and cash expenses.')),
                ('is_default_bank', models.BooleanField(default=False, help_text='Primary account for UPI/bank collections, QR codes, and bank transfers.')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_accounts', to='job_tickets.companyworkspace')),
            ],
            options={
                'ordering': ['-is_default_cash', '-is_default_bank', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('inflow', 'Inflow (Receipt)'), ('outflow', 'Outflow (Expense/Payment)'), ('transfer_in', 'Self Transfer (Received)'), ('transfer_out', 'Self Transfer (Sent)')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('transaction_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('description', models.CharField(max_length=255)),
                ('reference_no', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_account_transactions', to=settings.AUTH_USER_MODEL)),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_transactions', to='job_tickets.expense')),
                ('job_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_transactions', to='job_tickets.jobticket')),
                ('transfer_counterpart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counterparts', to='job_tickets.accounttransaction')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='job_tickets.financialaccount')),
            ],
            options={
                'ordering': ['-transaction_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='financial_account',
            field=models.ForeignKey(blank=True, help_text='Financial account from which this expense was paid.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='job_tickets.financialaccount'),
        ),
        migrations.AddField(
            model_name='jobticket',
            name='financial_account',
            field=models.ForeignKey(blank=True, help_text='Financial account (Cash drawer, Bank, UPI) where settlement payment was deposited.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settled_jobs', to='job_tickets.financialaccount'),
        ),
        migrations.AddIndex(
            model_name='financialaccount',
            index=models.Index(fields=['workspace', 'account_type'], name='job_tickets_workspa_22ec48_idx'),
        ),
        migrations.AddIndex(
            model_name='financialaccount',
            index=models.Index(fields=['workspace', 'is_active'], name='job_tickets_workspa_5bf02a_idx'),
        ),
        migrations.AddIndex(
            model_name='accounttransaction',
            index=models.Index(fields=['account', 'transaction_date'], name='job_tickets_account_8f56cf_idx'),
        ),
        migrations.AddIndex(
            model_name='accounttransaction',
            index=models.Index(fields=['transaction_type', 'transaction_date'], name='job_tickets_transac_1183a4_idx'),
        ),
    ]
