# Generated by Django 5.2.17 on 2026-09-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0092_seed_default_financial_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='include_ticket_signatures',
            field=models.BooleanField(default=True, help_text='Include signature section on job receipts and bills.'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='include_workshop_device_tag',
            field=models.BooleanField(default=True, help_text='Include tear-off workshop device tag on job ticket intake receipts.'),
        ),
    ]
