# Generated by Django 5.2.17 on 2026-09-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0093_companyprofile_include_ticket_signatures_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='technician_display_format',
            field=models.CharField(choices=[('id', 'Technician ID Number'), ('name', 'Technician Name')], default='id', help_text="Display technician by ID number or name under 'Serviced By' on printed bills.", max_length=10),
        ),
    ]
