# Generated by Django 5.2.17 on 2026-09-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0094_companyprofile_technician_display_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='include_bill_signatures',
            field=models.BooleanField(default=True, help_text='Include signature section on payment bills and invoices.'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='include_ticket_signatures',
            field=models.BooleanField(default=True, help_text='Include signature section on job intake receipts.'),
        ),
    ]
