# Generated by Django 5.2.17 on 2026-09-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0095_companyprofile_include_bill_signatures_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='include_bill_payment_details',
            field=models.BooleanField(default=True, help_text='Include payment settlement and bank details section on bills.'),
        ),
    ]
