# Generated by Django 5.2.17 on 2026-09-30 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0096_companyprofile_include_bill_payment_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttransaction',
            name='vendor_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_transactions', to='job_tickets.vendorpayment'),
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='financial_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_payments', to='job_tickets.financialaccount'),
        ),
    ]
