# Generated by Django 5.2.17 on 2026-09-30 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0097_accounttransaction_vendor_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttransaction',
            name='inventory_credit_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_transactions', to='job_tickets.inventorycreditpayment'),
        ),
        migrations.AddField(
            model_name='inventorycreditpayment',
            name='financial_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_credit_payments', to='job_tickets.financialaccount'),
        ),
    ]
