# Generated by Django 5.2.17 on 2026-10-01 13:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0098_accounttransaction_inventory_credit_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappintegrationsettings',
            name='daily_report_last_sent_date',
            field=models.DateField(blank=True, help_text='Last date for which the automatic daily report was dispatched.', null=True),
        ),
        migrations.AddField(
            model_name='whatsappintegrationsettings',
            name='daily_report_phone',
            field=models.CharField(blank=True, help_text='Recipient phone number(s) for daily report (comma-separated).', max_length=120),
        ),
        migrations.AddField(
            model_name='whatsappintegrationsettings',
            name='daily_report_template',
            field=models.TextField(blank=True, default='📊 *DAILY BUSINESS SUMMARY - {company_name}*\n📅 Date: {date} | Generated: {generated_time}\n\n🔧 *Operational Workload:*\n• 📥 New Jobs Received: {tickets_created_count}\n• ⚙️ Jobs Completed: {tickets_completed_count}\n• 🚚 Jobs Delivered / Closed: {tickets_delivered_count}\n• ⏳ Active Jobs Backlog: {active_tickets_count}\n\n💰 *Financials & Collections:*\n• 💵 Cash Receipts: ₹{cash_inflows}\n• 📱 Bank & UPI Receipts: ₹{bank_inflows}\n• 💳 Total Revenue: ₹{total_inflows}\n• 📤 Day Expenses Paid: ₹{total_expenses}\n\n🏦 *Cash Drawer Reconciliation:*\n• 🪙 Cash in Drawer: ₹{cash_drawer_balance}\n• 🌐 Total Liquid Position: ₹{total_liquid_balance}', help_text='Template used for the daily business summary WhatsApp message.'),
        ),
        migrations.AddField(
            model_name='whatsappintegrationsettings',
            name='daily_report_time',
            field=models.TimeField(default=datetime.time(21, 0), help_text='Scheduled time to dispatch automatic daily report (e.g. 21:00 for 9:00 PM).'),
        ),
        migrations.AddField(
            model_name='whatsappintegrationsettings',
            name='notify_daily_report',
            field=models.BooleanField(default=False, help_text='Automatically send daily business summary report via WhatsApp.'),
        ),
        migrations.AlterField(
            model_name='messagequeue',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('completed', 'Completed'), ('delivered', 'Delivered'), ('estimate', 'Estimate'), ('feedback', 'Feedback'), ('daily_report', 'Daily Report'), ('manual', 'Manual')], db_index=True, default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='whatsappnotificationlog',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('completed', 'Completed'), ('delivered', 'Delivered'), ('estimate', 'Estimate'), ('feedback', 'Feedback'), ('daily_report', 'Daily Report'), ('manual', 'Manual')], max_length=20),
        ),
        migrations.AlterField(
            model_name='whatsappnotificationlog',
            name='job_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_notifications', to='job_tickets.jobticket'),
        ),
    ]
