# Generated by Django 5.2.17 on 2026-10-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0099_whatsappintegrationsettings_daily_report_last_sent_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specializedservice',
            name='vendor_bill_number',
            field=models.CharField(blank=True, default='', help_text='Vendor invoice or bill number.', max_length=100),
        ),
    ]
