# Generated by Django 5.2.17 on 2026-10-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0101_jobticket_intake_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='alarm_time',
            field=models.DateTimeField(blank=True, help_text='Specific time to trigger the alarm (defaults to due_date or immediate if blank).', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='has_alarm',
            field=models.BooleanField(db_index=True, default=False, help_text='Sound an audible alarm alert when task is due or assigned.'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_open_to_all',
            field=models.BooleanField(db_index=True, default=False, help_text='If True, any technician can claim/accept this task from the shared pool.'),
        ),
    ]
