# Generated by Django 5.2.17 on 2026-10-04 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0102_task_alarm_time_task_has_alarm_task_is_open_to_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskattachment',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='job_tickets.taskmessage'),
        ),
    ]
