# Generated by Django 5.2.17 on 2026-10-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0104_alter_messagequeue_event_type_bulkcampaign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkcampaign',
            name='selected_client_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
