# Generated by Django 5.2.17 on 2026-10-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0105_bulkcampaign_selected_client_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this vendor is active and available for new jobs.'),
        ),
    ]
