# Generated by Django 5.2.17 on 2026-10-07 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tickets', '0106_vendor_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileAppRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('android', 'Android (APK)'), ('ios', 'iOS')], default='android', max_length=20)),
                ('version_name', models.CharField(help_text='e.g. 1.2.0', max_length=50)),
                ('version_code', models.PositiveIntegerField(help_text='Numeric build number, e.g. 12')),
                ('apk_file', models.FileField(blank=True, null=True, upload_to='app_releases/')),
                ('download_url', models.URLField(blank=True, help_text='External download URL if APK not uploaded directly.', max_length=500)),
                ('release_notes', models.TextField(blank=True, help_text="What's new in this version.")),
                ('min_version_code', models.PositiveIntegerField(default=1, help_text='Older builds below this will be forced to update.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_app_releases', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_releases', to='job_tickets.companyworkspace')),
            ],
            options={
                'ordering': ['-version_code', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MobileQrLoginToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('is_used', models.BooleanField(db_index=True, default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('device_info', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_login_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
